BEGIN;

ALTER TABLE data_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingestion_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchants ENABLE ROW LEVEL SECURITY;
ALTER TABLE venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE branch_source_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_licenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE discovery_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE dishes ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE moderation_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE recommendation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE branch_rating_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_review_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_submission_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchant_branch_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_risk_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE consumption_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_screening_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE branch_candidate_screenings ENABLE ROW LEVEL SECURITY;
ALTER TABLE branch_audit_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE branch_audit_batch_items ENABLE ROW LEVEL SECURITY;

-- 不创建 anon/authenticated policy：浏览器不能直接访问业务表，必须经过 Express API。
-- 数据库迁移账号和后端连接账号仍按 PostgreSQL 角色权限工作。

INSERT INTO schema_migrations(version) VALUES ('011_data_api_lockdown')
ON CONFLICT (version) DO NOTHING;

COMMIT;
